### ISSUE TITLE
homebridge not found by home app

### ISSUE THREAD

**Issue by ronneylira** [emlagowski/home-apps#1]
Hi, 

I've been trying to get Homebridge to work under k8s and cannot get to the stage where the Home app can actually connect to it.

You are the only one that I saw online working on it 😅 . Can you offer me some guidance as to where I might be overlooking something? 
I have the deployment/service/ingress all working for the UI, just the IOs that complain about it.

I checked your ymls and cannot find where I'm getting it wrong.

I have ports 8581 and 51403 configured in the deployment but only 8581 in the service (which I find it odd, but even if I expose the other one I still cannot reach it) The only thing that I could think of, is that the port 51403 is not exposed to the network, but I can't figure out what's the correct approach.

Did you face this issue?

**Comment by emlagowski** [comment]
hey @ronneylira :)

I have discussed that topic on [reddit](https://www.reddit.com/r/homebridge/comments/15rcict/homekit_hangs_with_homebridge_on_kubernetes_with/), because I had some problems achieving working solution.

You can provide your yamls in this topic so I can look at it.

> I have ports 8581 and 51403 configured in the deployment but only 8581 in the service (which I find it odd, but even if I expose the other one I still cannot reach it) The only thing that I could think of, is that the port 51403 is not exposed to the network, but I can't figure out what's the correct approach.

As I answered on reddit the second port is exposed by `hostNetwork: true` - all ports from your deployment are available via hostIP. Of course it is not ideal solution, but I was not able to get it working without that. I don't know if HomeKit is communicating over IP and not server name, so reverse proxy is not working this case. 

But I also needed volume, to get it working after pod restarts. Below is my full response to the same question on reddit.

---
I got it to the point where it is working between pods restarts, but I'm not 100% happy with my solution. As you can see here: https://github.com/emlagowski/home-apps/blob/main/homebridge/deployment.yml I have added two things:
- `hostNetwork: true` - my homebridge is behind reverse proxy so it should resolve my domain name, but it seems like HomeKit is connecting to it by resolved IP address.
- `homebridge-volume` - config and plugins are installed and provided at startup to the container, but I think there is still some important token / hash / ID or something which is generated on every restart. I think HomeKit is strict about that and when it changes integration fails, even if Homebridge works fine on its own.
```yaml
spec:
  volumes: 
  ...
  - name: homebridge-volume 
    persistentVolumeClaim: 
      claimName: homebridge-pvc 
  hostNetwork: true                 
  containers: ...
  - name: homebridge 
    volumeMounts:
      name: homebridge-volume 
      mountPath: /homebridge
```
So currently it is working fine, but not perfect. Homebridge is always in same state (when it comes to plugins etc.). If PVC is deleted, you just need to add it to HomeKit again.
I didn't have time for more investigation, but I think it is necessary to look at `/homebridge/persist/` directory.

**Comment by ronneylira** [comment]
Thanks for the quick response :)

I see some progress, now I can see an IP that's publicly visible in the resolve sec. 
but still, no luck getting it to be added in the home :/

this is my deployment:

`apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homebridge
  name: homebridge
  namespace: homebridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homebridge
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: homebridge
    spec:
      containers:
      - name: homebridge
        image: homebridge/homebridge:latest
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8581
            protocol: TCP
          - name: homebridge
            containerPort: 51403
            protocol: TCP
        resources:
          requests:
            cpu: "380m"
            memory: "200Mi"
          limits:
            cpu: "600m"
            memory: "480Mi"
        volumeMounts:
          - name: homebridge-volume
            mountPath: /homebridge
      restartPolicy: Always
      hostNetwork: true
      volumes:
      - name: homebridge-volume
        persistentVolumeClaim:
          claimName: homebridge-volume`

and the service

`---
kind: Service
apiVersion: v1
metadata:
  name: homebridge-tcp
  namespace: homebridge
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.2.47
  labels:
    app: homebridge
spec:
  selector:
    app: homebridge
  ports:
    - name: '8581'
      protocol: TCP
      port: 8581
      targetPort: 8581
    - name: '51403'
      protocol: TCP
      port: 51403
      targetPort: 51403
  type: LoadBalancer
  externalTrafficPolicy: Local`

if you can spot something odd, I would be very happy!

**Comment by emlagowski** [comment]
Try to format those yamls, because it is hard to spot the yaml formatting error. Use triple backticks: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

**Comment by ronneylira** [comment]
thanks for the tip man, but I already figured out the issue.
I had to change mDNS advertiser to get it working 🤷
but at least is working now! thanks for the help :)

**Comment by emlagowski** [comment]
Nice!
